type = "javascript"

name = "intro-quiz"
account_id = "582c765039f5eb2f5ed800472428ff05"
workers_dev = true

compatibility_date = "2022-05-24"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format = "service-worker"